import PoincareLib.Topology.Manifold.Smoothing.Polyhedral.General.TwoRayProjection
import Mathlib.Analysis.InnerProductSpace.Projection.FiniteDimensional

/-!
# The two-point normal-link projection space

Fixing one endpoint of a two-ray star identifies its entire
embedding-operator space with a nonempty convex set. This proves
the normal one-dimensional case of Cairns 1940, Section 11,
p. 807. See M76 derivation 39.
-/

set_option autoImplicit false

open Set Geometry ContinuousLinearMap

namespace PoincareMT.M76.Smoothing

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- Fixing the scalar frame generated by a vector is equivalent
to sending that vector to one. See Cairns p. 807 and M76 derivation 39. -/
theorem rightInverse_rayFrame_iff (u : E) (Q : E →L[ℝ] ℝ) :
    Function.RightInverse (toSpanSingleton ℝ u) Q ↔ Q u = 1 := by
  constructor
  · intro h
    simpa only [toSpanSingleton_apply_one] using h 1
  · intro h r
    change Q (r • u) = r
    rw [map_smul, h, smul_eq_mul, mul_one]

/-- The scalar endpoint constraints define a convex subset of the
actual ambient operator space. See Cairns p. 807 and M76 derivation 39. -/
theorem convex_twoPointOperatorSet (u v : E) :
    Convex ℝ {Q : E →L[ℝ] ℝ | Q u = 1 ∧ Q v < 0} := by
  intro Q hQ R hR a b ha hb hab
  constructor
  · change a * Q u + b * R u = 1
    rw [hQ.1, hR.1, mul_one, mul_one, hab]
  · change a * Q v + b * R v < 0
    exact convex_Iio (0 : ℝ) hQ.2 hR.2 ha hb hab

/-- A two-ray embedding with its first endpoint fixed has exactly
one linear equality and one strict endpoint inequality as its
coordinates. See Cairns p. 807 and M76 derivation 39. -/
noncomputable def twoPointFrameEmbeddingHomeomorph (u v : E)
    (hv : LinearIndependent ℝ ![u, v]) :
    FrameEmbeddingSpace (toSpanSingleton ℝ u) (twoRayStar u v) ≃ₜ
      {Q : E →L[ℝ] ℝ // Q u = 1 ∧ Q v < 0} :=
  Homeomorph.setCongr (by
    ext Q
    change (Function.RightInverse (toSpanSingleton ℝ u) Q ∧ InjOn Q (twoRayStar u v)) ↔ _
    rw [rightInverse_rayFrame_iff]
    exact and_congr_right (fun hu => injOn_twoRayStar_iff u v hv Q hu))

end PoincareMT.M76.Smoothing

namespace PoincareMT.M76.Smoothing

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [FiniteDimensional ℝ E]

/-- Independent endpoints admit an ambient scalar operator taking
values one and minus one. The construction extends coordinates on
their span by orthogonal projection.
See Cairns pp. 800, 807 and M76 derivation 39. -/
theorem nonempty_twoPointOperatorSet (u v : E) (hv : LinearIndependent ℝ ![u, v]) :
    ({Q : E →L[ℝ] ℝ | Q u = 1 ∧ Q v < 0} : Set (E →L[ℝ] ℝ)).Nonempty := by
  let V := Submodule.span ℝ (range ![u, v])
  let b : Module.Basis (Fin 2) ℝ V := Module.Basis.span hv
  let A : V →L[ℝ] ℝ := (b.coord 0 - b.coord 1).toContinuousLinearMap
  let Q : E →L[ℝ] ℝ := A.comp V.orthogonalProjectionOnto
  have hzero : (b 0 : E) = u := Module.Basis.coe_span_apply hv 0
  have hone : (b 1 : E) = v := Module.Basis.coe_span_apply hv 1
  refine ⟨Q, ?_, ?_⟩
  · rw [← hzero]
    simp [Q, A, Module.Basis.coord_apply]
  · rw [← hone]
    simp [Q, A, Module.Basis.coord_apply]

/-- The complete normalized projection space of an independent
two-point normal link is contractible in any finite ambient space.
See Cairns Section 11, p. 807, and M76 derivation 39. -/
theorem contractible_twoPointFrameEmbeddingSpace (u v : E)
    (hv : LinearIndependent ℝ ![u, v]) :
    ContractibleSpace (FrameEmbeddingSpace (toSpanSingleton ℝ u) (twoRayStar u v)) := by
  let : ContractibleSpace {Q : E →L[ℝ] ℝ // Q u = 1 ∧ Q v < 0} :=
    (convex_twoPointOperatorSet u v).contractibleSpace (nonempty_twoPointOperatorSet u v hv)
  exact (twoPointFrameEmbeddingHomeomorph u v hv).contractibleSpace

end PoincareMT.M76.Smoothing
