import PoincareLib.Geometry.RicciFlow.Soliton.Flow.Applications.Classification
import PoincareLib.Geometry.RicciFlow.Soliton.TwoDimensional.Ancient.Roundness
import PoincareLib.Geometry.RicciFlow.Soliton.TwoDimensional.Ancient.Sequence.Existence

/-!
# Two-dimensional ancient and shrinking-soliton classification

The exact frozen M19 conclusion combines the compact-round classification of
every actual asymptotic limit, the flow generated by each shrinking soliton,
and ancient roundness from a reduced-length minimizing rescaling sequence
constructed from the original ancient-solution hypotheses.

Morgan--Tian, Corollary 9.50, pp. 213--214.
-/

set_option autoImplicit false

open scoped Manifold ContDiff Bundle ENNReal Topology

universe u

namespace PoincareMT

variable {M : Type u} [TopologicalSpace M]
  [ChartedSpace (EuclideanSpace ℝ (Fin 2)) M]
  [IsManifold (𝓡 2) ∞ M] [MeasurableSpace M] [BorelSpace M]
  [T2Space M] [T3Space M] [SecondCountableTopology M] [ConnectedSpace M]

theorem twoDimensionalAncientAndShrinkingSolitonClassification
    (P : TwoDimensionalClassificationPredecessors (M := M)) :
    TwoDimensionalClassificationTheory (M := M) := by
  refine {
    asymptotic_round := P.asymptoticRoundTheory
    shrinking_soliton := exists_twoDimensionalShrinkingSolitonConclusion
    ancient_classification := ?_ }
  intro K
  have hsequence : Nonempty (AncientRescalingSequence K) :=
    K.exists_ancientRescalingSequence
  obtain ⟨S⟩ := hsequence
  exact ⟨P.ancientRoundCertificate_of_sequence K S⟩

end PoincareMT
