import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.Transport
import PoincareLib.Topology.Manifold.NeckCap.Cap.Core.SmoothDomain
import PoincareLib.Topology.Manifold.NeckCap.Cap.Bounds
import PoincareLib.Topology.Manifold.NeckCap.Cap.Core.BoundarySphere
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.Nearby
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.End
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.Boundary
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.Overlap
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.OutwardGraph
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.AlignedCores
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.MixedSlice
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.FrontierContact
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.ChainEncounter
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.ChainBoundary
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.ChainContainedSphere
import PoincareLib.Topology.Manifold.NeckCap.Cap.Closing.FiniteChain
import PoincareLib.Topology.Manifold.NeckCap.Cap.ProjectiveCoordinates
import PoincareLib.Topology.Manifold.NeckCap.Cap.Projective.BoundaryLift
import PoincareLib.Topology.Manifold.NeckCap.Cap.Projective.CoreLift
import PoincareLib.Topology.Manifold.NeckCap.Cap.Core.Truncation
import PoincareLib.Topology.Manifold.NeckCap.Cap.Core.TruncatedDomain
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.FrontierNeck
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.FrontierExtension
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.Tails
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.NegativeEnd
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.ChainIntersection
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.ChainTail
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.ClosingTails
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.Orientation
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.FiniteChain
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.FrontierCylinder
import PoincareLib.Topology.Manifold.NeckCap.Cap.Attachment.OutgoingChain
import PoincareLib.Topology.Manifold.NeckCap.Cap.Chain.Extension
import PoincareLib.Topology.Manifold.NeckCap.Cap.Chain.Frontier
import PoincareLib.Topology.Manifold.NeckCap.Cap.Chain.SmoothDomain
import PoincareLib.Topology.Manifold.NeckCap.Cap.Chain.Complement
import PoincareLib.Topology.Manifold.NeckCap.Cap.Growth.NestedCore
import PoincareLib.Topology.Manifold.NeckCap.Cap.Growth.DisjointBoundary
import PoincareLib.Topology.Manifold.NeckCap.Cap.Growth.Termination
import PoincareLib.Topology.Manifold.NeckCap.Cap.Growth.Maximal
import PoincareLib.Topology.Manifold.NeckCap.Cap.Core.EnclosingRegion
import PoincareLib.Geometry.RicciFlow.CanonicalNeighborhood.Neck.Overlap.AxialMonotonicity
import PoincareLib.Geometry.RicciFlow.CanonicalNeighborhood.Neck.Overlap.SphereContact

/-! # Core, boundary collar, and complementary geometry of caps -/
