import PoincareLib.Topology.Manifold.ThreeDimensional.Triangulation.Polyhedral.FiniteGeometricCoordinates
import PoincareLib.Topology.Manifold.Smoothing.Imports.Topology.FiniteOrderComplex

/-! Source-name compatibility for the unchanged Mapher smoothing proofs. -/

namespace PoincareMT.Proofs.M02.Topology

export Poincare.Topology (simplicialComplex_convex_weights_unique finite_simplicialComplex_vertices finiteGeometricCoordinates finiteGeometricCoordinates_faces finiteGeometricCoordinates_finite finiteGeometricCoordinates_space geometricVertexWeights geometricVertexWeights_apply geometricVertexWeights_sum geometricVertexWeights_sum_smul geometricVertexWeights_support finiteGeometricEvaluation finiteGeometricEvaluation_injective finiteGeometricEvaluation_mem finiteGeometricEvaluation_surjective finiteGeometricCoordinates_isCompact finiteGeometricHomeomorph finiteGeometricHomeomorph_apply)

end PoincareMT.Proofs.M02.Topology
