import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Components
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Pinching
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Topology
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.SurgeryInput
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.Regions
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CapCurvature
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.NeckCurvature.Ambient
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.NeckBoundary
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.NeckSelection
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.IntersectingRegions
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.AttainedFrontier
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.EndCorrespondence
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CapDirection
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CoreComponents
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CutTopology
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.SelectedGeometry
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.Orientation
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CutGeometry.Conversion
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.Boundary
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.ProperEnds
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.NeckGeometry
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.RicciComparison.SphereTransport
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.CapContainment
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.ProperHorn
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.HornNonFilling
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.RetainedCompactness.Policy
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.RetainedCompactness.FiniteCutCover
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.Selection.Transport
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.Selection.Pruning
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Pinching
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Compactness.Global
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Topology.Punctures
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Topology.Polar
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Topology.LocalModel
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Topology.ProjectivePlane
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Caps.Boundary
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Retained.Post
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Retained.Identification
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Gluing.Retained.Policy
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.Disappearing
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.LimitPullback
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.StrongBoundary.OldCylinder
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.StrongBoundary.HistoryCylinder
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.Policy
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.Reference
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.StrongBoundary.RestartCylinder
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.StrongBoundary.Assembled
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Event.Operation
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Extinction.ScalarTail
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Extinction.Volume
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Extinction.Flow.Admissible
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Extinction.Flow.Properties
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Extinction.Conclusion
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Restart.Flow.Maximality
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Restart.Flow.Properties
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Restart.Flow.FiniteEnd
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Restart.Flow.CanonicalTail
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Restart.Conclusion
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Restart.EndCover
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Restart.SmallConstant
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.RegionAlternative
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.TubeCalibration
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.Capped.LowPointHorn
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.Capped.WholeComponent
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.CappedLowPoint
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.CapBoundary
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.CapFrontier
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.FromStrongCenters
import PoincareLib.Geometry.RicciFlow.Surgery.Continuation.Construction.Terminal.Ends.CalibratedHorn.Capped.StrongCenters

/-! Checked terminal geometry used in the branch-correct continuation construction. -/
